--- #EC2 Key module example
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Create a New Key Pair - MyKeyPairTestAWS
    ec2_key:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      name: MyKeyPairTestAWS
      region: us-east-1
      state: present
